require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Christopher_Burton' do

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Christopher_BurtonTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
